<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[launch Browser]]>
    </line>
    <line>
      <![CDATA[click on login button]]>
    </line>
    <line>
      <![CDATA[click on continue button]]>
    </line>
    <line>
      <![CDATA[tc is failed TC name isvalidateUserID]]>
    </line>
    <line>
      <![CDATA[logging out]]>
    </line>
    <line>
      <![CDATA[closing browser]]>
    </line>
  </reporter-output>
  <suite started-at="2022-07-07T16:25:44 IST" name="Suite" finished-at="2022-07-07T16:25:57 IST" duration-ms="13231">
    <groups>
    </groups>
    <test started-at="2022-07-07T16:25:44 IST" name="Test" finished-at="2022-07-07T16:25:57 IST" duration-ms="13231">
      <class name="KiteTest.ValidateKiteUserIDByListener">
        <test-method is-config="true" signature="launchBrowser()[pri:0, instance:KiteTest.ValidateKiteUserIDByListener@957e06]" started-at="2022-07-07T16:25:44 IST" name="launchBrowser" finished-at="2022-07-07T16:25:52 IST" duration-ms="8057" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[launch Browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- launchBrowser -->
        <test-method is-config="true" signature="loginToKiteApp()[pri:0, instance:KiteTest.ValidateKiteUserIDByListener@957e06]" started-at="2022-07-07T16:25:52 IST" name="loginToKiteApp" finished-at="2022-07-07T16:25:53 IST" duration-ms="696" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[click on login button]]>
            </line>
            <line>
              <![CDATA[click on continue button]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginToKiteApp -->
        <test-method signature="validateUserID()[pri:0, instance:KiteTest.ValidateKiteUserIDByListener@957e06]" started-at="2022-07-07T16:25:53 IST" name="validateUserID" finished-at="2022-07-07T16:25:54 IST" duration-ms="1337" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: null
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.fail(Assert.java:106)
at KiteTest.ValidateKiteUserIDByListener.validateUserID(ValidateKiteUserIDByListener.java:64)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[tc is failed TC name isvalidateUserID]]>
            </line>
          </reporter-output>
        </test-method> <!-- validateUserID -->
        <test-method is-config="true" signature="logOutFromKite()[pri:0, instance:KiteTest.ValidateKiteUserIDByListener@957e06]" started-at="2022-07-07T16:25:54 IST" name="logOutFromKite" finished-at="2022-07-07T16:25:56 IST" duration-ms="1223" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[logging out]]>
            </line>
          </reporter-output>
        </test-method> <!-- logOutFromKite -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:KiteTest.ValidateKiteUserIDByListener@957e06]" started-at="2022-07-07T16:25:56 IST" name="closeBrowser" finished-at="2022-07-07T16:25:57 IST" duration-ms="1321" status="PASS">
          <reporter-output>
            <line>
              <![CDATA[closing browser]]>
            </line>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- KiteTest.ValidateKiteUserIDByListener -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
